version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=359538883686.dkr.ecr.us-east-1.amazonaws.com/test-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 359538883686.dkr.ecr.us-east-1.amazonaws.com/test-repo:latest .
      - docker tag 359538883686.dkr.ecr.us-east-1.amazonaws.com/test-repo:latest 359538883686.dkr.ecr.us-east-1.amazonaws.com/test-repo:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 359538883686.dkr.ecr.us-east-1.amazonaws.com/test-repo:latest
      - docker push 359538883686.dkr.ecr.us-east-1.amazonaws.com/test-repo:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"order-service","imageUri":"%s"}]' 359538883686.dkr.ecr.us-east-1.amazonaws.com/test-repo:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - target/order-service.jar

